context:
  version: "2.34.1"

package:
  name: dotenvx
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@dotenvx/dotenvx/-/dotenvx-${{ version }}.tgz
  sha256: 10a1ca7923043b4345ca32897533891b687d102b7443f76df647902cb1fa2b3b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - dotenvx --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: a better dotenv–from the creator of `dotenv`
  homepage: https://github.com/dotenvx/dotenvx
  repository: https://github.com/dotenvx/dotenvx

extra:
  recipe-maintainers:
    - danielnachun
