context:
  version: "1.40.1"

package:
  name: dotenvx
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@dotenvx/dotenvx/-/dotenvx-${{ version }}.tgz
  sha256: 151a76046c2f61114c788cdc8bec3aa371e3db7be6bdc561634e041f0d45465a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - dotenvx --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: a better dotenv–from the creator of `dotenv`
  homepage: https://github.com/dotenvx/dotenvx
  repository: https://github.com/dotenvx/dotenvx

extra:
  recipe-maintainers:
    - danielnachun
