context:
  version: "1.48.4"

package:
  name: dotenvx
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@dotenvx/dotenvx/-/dotenvx-${{ version }}.tgz
  sha256: 62cc554bbb83a8d76237535cbc6164697b5448281f20708e83e0be0da4a46caf

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - dotenvx --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: a better dotenv–from the creator of `dotenv`
  homepage: https://github.com/dotenvx/dotenvx
  repository: https://github.com/dotenvx/dotenvx

extra:
  recipe-maintainers:
    - danielnachun
