context:
  version: "1.47.3"

package:
  name: dotenvx
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@dotenvx/dotenvx/-/dotenvx-${{ version }}.tgz
  sha256: 09389a2b178a530878188636e0206dfe79ecd013a61da5fa6e142be7c36f879c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - dotenvx --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: a better dotenv–from the creator of `dotenv`
  homepage: https://github.com/dotenvx/dotenvx
  repository: https://github.com/dotenvx/dotenvx

extra:
  recipe-maintainers:
    - danielnachun
