context:
  version: "1.55.1"

package:
  name: dotenvx
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@dotenvx/dotenvx/-/dotenvx-${{ version }}.tgz
  sha256: 99918a44ddbfea234708114fcbd0f686dab7bc4f4f5c9ab0abf324499b1c65d5

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - dotenvx --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: a better dotenv–from the creator of `dotenv`
  homepage: https://github.com/dotenvx/dotenvx
  repository: https://github.com/dotenvx/dotenvx

extra:
  recipe-maintainers:
    - danielnachun
